---
- hosts: databases
  become: yes
  tasks:
  - name: install apache
    yum: 
      name: httpd
      state: latest
  - name: create a file if it doesnt exist
    file:
     state: touch
     path: /var/www/html/index.html
  - name:
    lineinfile:
     state: present
     dest:  /var/www/html/index.html
     line: Hostname={{ansible_hostname}}
  - name: restart apache
    service: 
     name: httpd
     state: reloaded
     enabled: yes
